"use client";

import { useEffect, useMemo, useState } from "react";
import { AppSidebar, MobileNavigation } from "./app-navigation";
import { PlusIcon, XIcon } from "./icons";

type Status = "Planning" | "Active" | "Delayed" | "Completed";
type Priority = "High" | "Medium" | "Low";
type Category = "Project" | "Goal" | "Book" | "Course" | "Certification" | "Job Search" | "University" | "Simple Task";
type ProgressType = "Pages" | "Subtasks";
type Goal = { id:string; title:string; category:Category; priority:Priority; status:Status; startDate:string; targetDate:string; progressType:ProgressType; current:number; total:number; milestones:{id:string;name:string;done:boolean}[]; completedAt?:string };

const key="tasksprint.goals.v4";
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const seed:Goal[]=[];
const categories:Category[]=["Project","Goal","Book","Course","Certification","Job Search","University","Simple Task"];
const progressTypes:ProgressType[]=["Pages","Subtasks"];
const defaultProgressMap:Record<Category,ProgressType>={Project:"Subtasks",Goal:"Subtasks",Book:"Pages",Course:"Subtasks",Certification:"Subtasks","Job Search":"Subtasks",University:"Subtasks","Simple Task":"Subtasks"};
const defaultProgress=(category:Category):ProgressType=>defaultProgressMap[category];
const progressFor=(g:Goal)=>{const checklist=g.progressType==="Subtasks";const current=checklist?g.milestones.filter(m=>m.done).length:g.current||0,total=checklist?g.milestones.length:g.total||0;return{current,total,percent:total?Math.min(100,Math.round(current/total*100)):0,label:`${current} of ${total} ${g.progressType.toLowerCase()}`}};
const migrate=(g:Partial<Goal>&Record<string,unknown>):Goal=>{const old=String(g.category);const category:Category=old==="Job search"?"Job Search":old==="Learning"?"Course":old==="Personal"?"Goal":categories.includes(old as Category)?old as Category:"Goal";const progressType:ProgressType=String(g.progressType)==="Pages"?"Pages":"Subtasks";const oldStatus=String(g.status);const status:Status=oldStatus==="Done"?"Completed":oldStatus==="On hold"?"Delayed":["Planning","Active","Delayed","Completed"].includes(oldStatus)?oldStatus as Status:"Planning";return{...g,id:String(g.id||uid()),title:String(g.title||"Untitled"),category,priority:(g.priority||"Medium") as Priority,status,startDate:String(g.startDate||today()),targetDate:String(g.targetDate||today()),progressType,current:Number(g.current||0),total:Number(g.total||0),milestones:Array.isArray(g.milestones)?g.milestones:[]} as Goal};
const format=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
const displayTitle=(title:string)=>title.length>35?`${title.slice(0,35).trimEnd()}...`:title;
const typeClass=(category:Category)=>`type-${category.toLowerCase().replaceAll(" ","-")}`;
const formatTimeline=(start:string,end:string)=>{const a=new Date(`${start}T12:00:00`),b=new Date(`${end}T12:00:00`);if(a.getFullYear()===b.getFullYear()){if(a.getMonth()===b.getMonth())return `${a.toLocaleDateString("en-US",{month:"short",day:"numeric"})} – ${b.getDate()}, ${b.getFullYear()}`;return `${a.toLocaleDateString("en-US",{month:"short",day:"numeric"})} – ${b.toLocaleDateString("en-US",{month:"short",day:"numeric"})}, ${b.getFullYear()}`}return `${format(start)} – ${format(end)}`};

function GoalForm({goal,onClose,onSave}:{goal?:Goal;onClose:()=>void;onSave:(g:Goal)=>void}){
 const [g,setG]=useState<Goal>(goal||{id:uid(),title:"",category:"Project",priority:"Medium",status:"Planning",startDate:today(),targetDate:today(),progressType:"Subtasks",current:0,total:0,milestones:[]});
 const [subtask,setSubtask]=useState("");
 const set=<K extends keyof Goal>(k:K,v:Goal[K])=>setG(x=>({...x,[k]:v}));
 return <div className="dialog-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="goal-dialog"><header className="dialog-header"><div><span className="eyebrow">Finish line</span><h2>{goal?"Edit goal":"New goal"}</h2></div><button className="icon-button" onClick={onClose}><XIcon/></button></header><form onSubmit={e=>{e.preventDefault();const checklistDone=g.progressType==="Subtasks"&&g.milestones.length>0&&g.milestones.every(m=>m.done);const status=checklistDone?"Completed":g.status;onSave({...g,status,completedAt:status==="Completed"?g.completedAt||today():undefined})}}>
  <label className="field"><span>Title</span><input autoFocus required value={g.title} onChange={e=>set("title",e.target.value)}/></label>
  <div className="form-grid"><label className="field"><span>Type</span><select value={g.category} onChange={e=>{const category=e.target.value as Category;setG(x=>({...x,category,progressType:defaultProgress(category)}))}}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Priority</span><select value={g.priority} onChange={e=>set("priority",e.target.value as Priority)}>{["High","Medium","Low"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Status</span><select value={g.status} onChange={e=>set("status",e.target.value as Status)}>{["Planning","Active","Delayed","Completed"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Progress By</span><select value={g.progressType} onChange={e=>set("progressType",e.target.value as ProgressType)}>{progressTypes.map(x=><option key={x}>{x}</option>)}</select></label>{g.progressType==="Pages"&&<><label className="field"><span>Current page</span><input type="number" min="0" value={g.current} onChange={e=>set("current",+e.target.value)}/></label><label className="field"><span>Total pages</span><input type="number" min="0" value={g.total} onChange={e=>set("total",+e.target.value)}/></label></>}<label className="field"><span>Started on</span><input type="date" required value={g.startDate} onChange={e=>set("startDate",e.target.value)}/></label><label className="field"><span>Due date</span><input type="date" required value={g.targetDate} onChange={e=>set("targetDate",e.target.value)}/></label></div>
  {g.progressType==="Subtasks"&&<section className="subtask-editor"><div><strong>Subtasks</strong><span>{g.milestones.filter(m=>m.done).length} of {g.milestones.length} completed</span></div>{g.milestones.map(m=><label key={m.id}><input type="checkbox" checked={m.done} onChange={()=>setG(current=>{const milestones=current.milestones.map(x=>x.id===m.id?{...x,done:!x.done}:x),complete=milestones.length>0&&milestones.every(x=>x.done);return{...current,milestones,status:complete?"Completed":current.status==="Completed"?"Active":current.status}})}/><span>{m.name}</span><button type="button" onClick={()=>set("milestones",g.milestones.filter(x=>x.id!==m.id))}>×</button></label>)}<div className="subtask-add"><input value={subtask} onChange={e=>setSubtask(e.target.value)} placeholder="Add a subtask"/><button type="button" onClick={()=>{if(subtask.trim()){set("milestones",[...g.milestones,{id:uid(),name:subtask.trim(),done:false}]);setSubtask("")}}}>Add</button></div></section>}
  <div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button">Save goal</button></div>
 </form></section></div>
}

function GoalGroup({title,goals,colour,onEdit,onToggle,onAdd}:{title:string;goals:Goal[];colour:string;onEdit:(g:Goal)=>void;onToggle:(g:Goal)=>void;onAdd:()=>void}){
 const [open,setOpen]=useState(true);
 return <section className="board-group" style={{"--group":colour} as React.CSSProperties}><button className="board-group-title" onClick={()=>setOpen(!open)}><span>{open?"⌄":"›"}</span>{title}<small>{goals.length}</small></button>{open&&<div className="board-table"><div className="board-row board-head"><span/><span>Goal</span><span>Type</span><span>Progress</span><span>Status</span><span>Timeline</span><span>Due date</span><span>Priority</span></div>{goals.map(g=>{const p=progressFor(g);return <button className={`board-row ${typeClass(g.category)}`} key={g.id} onClick={()=>onEdit(g)}><span><i className={g.status==="Completed"?"checked":""} onClick={e=>{e.stopPropagation();onToggle(g)}}>{g.status==="Completed"&&"✓"}</i></span><strong title={g.title}>{displayTitle(g.title)}</strong><span className="board-type">{g.category}</span><span className="board-progress"><em>{p.label}</em><i><b style={{width:`${p.percent}%`}}/></i><small>{p.percent}%</small></span><span className={`board-status ${g.status.toLowerCase()}`}>{g.status}</span><span className="board-timeline"><b>{formatTimeline(g.startDate,g.targetDate)}</b></span><span className={`board-due ${g.status!=="Completed"&&g.targetDate<today()?"overdue":""}`}>{format(g.targetDate)}</span><span className={`board-priority ${g.priority.toLowerCase()}`}>{g.priority}</span></button>})}<button className="board-add-row" onClick={onAdd}><span/><span>＋ Add goal</span></button></div>}</section>
}

export function GoalsDashboard(){
 const [goals,setGoals]=useState(seed),[editing,setEditing]=useState<Goal|"new"|null>(null),[ready,setReady]=useState(false),[search,setSearch]=useState(""),[priority,setPriority]=useState<Priority|"All">("All"),[sortAsc,setSortAsc]=useState(true);
 useEffect(()=>{queueMicrotask(()=>{try{const saved=localStorage.getItem(key);if(saved)setGoals((JSON.parse(saved) as (Partial<Goal>&Record<string,unknown>)[]).map(migrate))}catch{}setReady(true)})},[]);useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(goals))},[goals,ready]);
 const shown=useMemo(()=>goals.filter(g=>g.title.toLowerCase().includes(search.toLowerCase())&&(priority==="All"||g.priority===priority)).sort((a,b)=>(sortAsc?1:-1)*a.targetDate.localeCompare(b.targetDate)),[goals,search,priority,sortAsc]);
 const save=(g:Goal)=>{setGoals(xs=>xs.some(x=>x.id===g.id)?xs.map(x=>x.id===g.id?g:x):[g,...xs]);setEditing(null)};
 const toggle=(g:Goal)=>save({...g,status:g.status==="Completed"?"Active":"Completed",completedAt:g.status==="Completed"?undefined:today()});
 return <main className="app-shell"><AppSidebar active="goals"><div className="sidebar-card"><span>Weekly review</span><strong>Keep your finish lines visible.</strong><small>Review status and deadlines once a week.</small></div></AppSidebar><section className="main-content board-content"><header className="board-page-title"><div><span className="eyebrow">Your finish lines</span><h1>Goals &amp; Projects</h1><p>Plan the big things. Keep every deadline in sight.</p></div><button className="primary-button add-task" aria-label="Add goal" onClick={()=>setEditing("new")}><PlusIcon/><span>Add goal</span></button></header><div className="board-toolbar"><label className="board-search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search goals"/></label><label className="board-filter">◇ <select value={priority} onChange={e=>setPriority(e.target.value as Priority|"All")}><option value="All">All priorities</option><option>High</option><option>Medium</option><option>Low</option></select></label><button onClick={()=>setSortAsc(!sortAsc)}>⇅ Due date</button><span className="board-count">{shown.length} goals</span></div><div className="board-groups"><GoalGroup title="To-Do" colour="#4f83cc" goals={shown.filter(g=>g.status!=="Completed")} onEdit={setEditing} onToggle={toggle} onAdd={()=>setEditing("new")}/><GoalGroup title="Completed" colour="#42a86b" goals={shown.filter(g=>g.status==="Completed")} onEdit={setEditing} onToggle={toggle} onAdd={()=>setEditing("new")}/></div></section><MobileNavigation active="goals"/>{editing&&<GoalForm goal={editing==="new"?undefined:editing} onClose={()=>setEditing(null)} onSave={save}/>}</main>
}
